2025-10-22 17:43:44,231 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 17:43:44,547 - ERROR - 오늘 종가 확인 실패: HTTPSConnectionPool(host='fchart.stock.naver.com', port=443): Max retries exceeded with url: /sise.nhn?timeframe=day&count=6000&requestType=0&symbol=005930 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
2025-10-22 17:56:42,568 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 17:56:42,804 - ERROR - 오늘 종가 확인 실패: HTTPSConnectionPool(host='fchart.stock.naver.com', port=443): Max retries exceeded with url: /sise.nhn?timeframe=day&count=6000&requestType=0&symbol=005930 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
2025-10-22 18:07:34,234 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 18:07:34,237 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 18:07:34,519 - ERROR - 오늘 종가 확인 실패: HTTPSConnectionPool(host='fchart.stock.naver.com', port=443): Max retries exceeded with url: /sise.nhn?timeframe=day&count=6000&requestType=0&symbol=005930 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
2025-10-22 18:16:09,044 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 18:16:09,291 - ERROR - 오늘 종가 확인 실패: HTTPSConnectionPool(host='fchart.stock.naver.com', port=443): Max retries exceeded with url: /sise.nhn?timeframe=day&count=6000&requestType=0&symbol=005930 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
2025-10-22 18:53:54,218 - INFO - 오늘 종가 데이터 확인 중...
2025-10-22 18:53:54,479 - ERROR - 오늘 종가 확인 실패: HTTPSConnectionPool(host='fchart.stock.naver.com', port=443): Max retries exceeded with url: /sise.nhn?timeframe=day&count=6000&requestType=0&symbol=005930 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))
